# Generated by Django 4.0.4 on 2022-05-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_plant_gardenplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenplant',
            name='number_planted',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='days_to_harvest',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='depth_inches',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
