# Generated by Django 4.0.4 on 2022-05-30 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_gardenplant_number_planted_plant_days_to_harvest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenplant',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='garden.garden'),
        ),
    ]
